#!/bin/bash
# Windows EXE 编译步骤脚本
# 由于 PyInstaller 不支持跨平台编译，需要在 Windows 环境中执行

echo "=========================================="
echo "Windows EXE 编译指南"
echo "=========================================="
echo ""
echo "由于您在 Mac 系统上，无法直接编译 Windows exe。"
echo "请选择以下方案之一："
echo ""
echo "方案一：使用 GitHub Actions（推荐）"
echo "----------------------------------------"
echo "1. 初始化 Git 仓库："
echo "   cd /Users/Sam/git/kill"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo ""
echo "2. 在 GitHub 上创建新仓库"
echo ""
echo "3. 推送代码："
echo "   git remote add origin <your-github-repo-url>"
echo "   git push -u origin main"
echo ""
echo "4. GitHub Actions 会自动编译，完成后在 Actions 页面下载 exe"
echo ""
echo "方案二：使用 Windows 虚拟机"
echo "----------------------------------------"
echo "1. 在 Windows 虚拟机中安装 Python 3.11"
echo "2. 复制项目文件到虚拟机"
echo "3. 执行以下命令："
echo "   pip install -r requirements.txt"
echo "   pip install pyinstaller"
echo "   pyinstaller build.spec"
echo "4. exe 文件在 dist/DomainKiller.exe"
echo ""
echo "=========================================="

